server:
  port: 8080
swagger:
  enabled: true
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/guoran?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
#  mapper-locations: classpath:com/guoran/server/weicustomer/repository/xml/*.xml
  mapper-locations: classpath*:com/guoran/server/**/repository/xml/*.xml
  type-aliases-package: com.guoran.server.**.model
#  configuration:
#    map-underscore-to-camel-case: true
